const routes = {
    origin: '/',
    home: '/home',
    login: '/login',
    register: '/register',
    products: '/products',
    productDetail: '/product/:id',
    userProfile: '/user/profile',
    user: '/user',
    userAddress: '/user/address',
    userAddressAdd: '/user/address/add',
    userAddressEdit: '/user/address/edit',
    userPassword: '/user/password',
    userOrders: '/user/orders',
    userCart: '/user/cart',
    userCheckout: '/user/checkout',
    orderDetail: '/user/order/:id',
    forgotPassword: '/forgot-password',
    sendVerifyCode: '/forgot-password/send',
    verifyCode: '/forgot-password/verify',
    resetPassword: '/forgot-password/reset',
    notFound: '*',
};

export default routes;
